// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsFlutterMindfulMinutesPlugin(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashFlutterMindfulMinutesPlugin(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsFlutterMindfulMinutesPlugin(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsFlutterMindfulMinutesPlugin(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsFlutterMindfulMinutesPlugin(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsFlutterMindfulMinutesPlugin(lhsKey, rhsKey) {
          if deepEqualsFlutterMindfulMinutesPlugin(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsFlutterMindfulMinutesPlugin(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashFlutterMindfulMinutesPlugin(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashFlutterMindfulMinutesPlugin(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashFlutterMindfulMinutesPlugin(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashFlutterMindfulMinutesPlugin(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashFlutterMindfulMinutesPlugin(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashFlutterMindfulMinutesPlugin(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum AuthorizationStatus: Int {
  case denied = 0
  case notDetermined = 1
  case authorized = 2
  case unknown = 3
}

enum RequestStatusForAuthorization: Int {
  case shouldRequest = 0
  case unnecessary = 1
  case unknown = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct AuthorizationResult: Hashable {
  var success: Bool
  var status: AuthorizationStatus


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AuthorizationResult? {
    let success = pigeonVar_list[0] as! Bool
    let status = pigeonVar_list[1] as! AuthorizationStatus

    return AuthorizationResult(
      success: success,
      status: status
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      status,
    ]
  }
  static func == (lhs: AuthorizationResult, rhs: AuthorizationResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsFlutterMindfulMinutesPlugin(lhs.success, rhs.success) && deepEqualsFlutterMindfulMinutesPlugin(lhs.status, rhs.status)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AuthorizationResult")
    deepHashFlutterMindfulMinutesPlugin(value: success, hasher: &hasher)
    deepHashFlutterMindfulMinutesPlugin(value: status, hasher: &hasher)
  }
}

private class FlutterMindfulMinutesPluginPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AuthorizationStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RequestStatusForAuthorization(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return AuthorizationResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class FlutterMindfulMinutesPluginPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AuthorizationStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? RequestStatusForAuthorization {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? AuthorizationResult {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FlutterMindfulMinutesPluginPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FlutterMindfulMinutesPluginPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FlutterMindfulMinutesPluginPigeonCodecWriter(data: data)
  }
}

class FlutterMindfulMinutesPluginPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = FlutterMindfulMinutesPluginPigeonCodec(readerWriter: FlutterMindfulMinutesPluginPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FlutterMindfulMinutesHostApi {
  func isAvailable(completion: @escaping (Result<Bool, Error>) -> Void)
  func getAuthorizationStatus(completion: @escaping (Result<AuthorizationStatus, Error>) -> Void)
  func getRequestForAuthorizationStatus(completion: @escaping (Result<RequestStatusForAuthorization, Error>) -> Void)
  func requestAuthorization(completion: @escaping (Result<Bool, Error>) -> Void)
  func writeMindfulMinutes(startSeconds: Int64, endSeconds: Int64, completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FlutterMindfulMinutesHostApiSetup {
  static var codec: FlutterStandardMessageCodec { FlutterMindfulMinutesPluginPigeonCodec.shared }
  /// Sets up an instance of `FlutterMindfulMinutesHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FlutterMindfulMinutesHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let isAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_mindful_minutes.FlutterMindfulMinutesHostApi.isAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isAvailableChannel.setMessageHandler { _, reply in
        api.isAvailable { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isAvailableChannel.setMessageHandler(nil)
    }
    let getAuthorizationStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_mindful_minutes.FlutterMindfulMinutesHostApi.getAuthorizationStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAuthorizationStatusChannel.setMessageHandler { _, reply in
        api.getAuthorizationStatus { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAuthorizationStatusChannel.setMessageHandler(nil)
    }
    let getRequestForAuthorizationStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_mindful_minutes.FlutterMindfulMinutesHostApi.getRequestForAuthorizationStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getRequestForAuthorizationStatusChannel.setMessageHandler { _, reply in
        api.getRequestForAuthorizationStatus { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getRequestForAuthorizationStatusChannel.setMessageHandler(nil)
    }
    let requestAuthorizationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_mindful_minutes.FlutterMindfulMinutesHostApi.requestAuthorization\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestAuthorizationChannel.setMessageHandler { _, reply in
        api.requestAuthorization { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestAuthorizationChannel.setMessageHandler(nil)
    }
    let writeMindfulMinutesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_mindful_minutes.FlutterMindfulMinutesHostApi.writeMindfulMinutes\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writeMindfulMinutesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let startSecondsArg = args[0] as! Int64
        let endSecondsArg = args[1] as! Int64
        api.writeMindfulMinutes(startSeconds: startSecondsArg, endSeconds: endSecondsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      writeMindfulMinutesChannel.setMessageHandler(nil)
    }
  }
}
