import 'package:flutter_mindful_minutes/flutter_mindful_minutes.g.dart';
export 'package:flutter_mindful_minutes/flutter_mindful_minutes.g.dart' show AuthorizationStatus, RequestStatusForAuthorization, AuthorizationResult;

/// FlutterMindfulMinutes is a Flutter Plugin that allows you
/// to write mindful minutes to the system on Android and iOS.
class FlutterMindfulMinutes {

  /// The host API for communicating with the native platform.
  /// This is generated by Pigeon and should not be modified manually.
  final _api = FlutterMindfulMinutesHostApi();

  /// Checks if the mindful minutes API is available on the current device.
  Future<bool> isAvailable() => _api.isAvailable();  

  /// Checks if the app has permission to write mindful minutes.
  Future<AuthorizationStatus> getAuthorizationStatus() => _api.getAuthorizationStatus();  

  /// Checks if the app should request permission to write mindful minutes.
  Future<RequestStatusForAuthorization> getRequestForAuthorizationStatus() => 
    _api.getRequestForAuthorizationStatus();  

  /// Requests to open the system dialog/sheet to request permission to write and read mindful minutes.
  /// Note:
  /// - the result doesn't mean that the user granted permission
  /// - the result doesn't mean that the system dialog/sheet was shown (it may have been suppressed by the system)
  Future<bool> requestAuthorization() => _api.requestAuthorization();

  /// Writes mindful minutes to the system.
  /// [startTime] and [endTime] are the start and end times of
  /// mindful minutes exercised.
  // Communication between platforms is done in seconds.
  Future<void> writeMindfulMinutes(DateTime startTime, DateTime endTime) =>    
    _api.writeMindfulMinutes(
      (startTime.millisecondsSinceEpoch / 1000).toInt(),
      (endTime.millisecondsSinceEpoch / 1000).toInt(),
    );

}

