import 'package:flutter_mindful_minutes/flutter_mindful_minutes.g.dart';

/// FlutterMindfulMinutes is a Flutter Plugin that allows you
/// to write mindful minutes to the system on Android and iOS.
class FlutterMindfulMinutes {

  /// The host API for communicating with the native platform.
  /// This is generated by Pigeon and should not be modified manually.
  final _api = FlutterMindfulMinutesHostApi();

  /// Checks if the mindful minutes API is available on the current device.
  Future<bool> isAvailable() async {
    return await _api.isAvailable();
  }

  /// Requests permission to write mindful minutes.
  /// This will show a system dialog to the user.
  /// Returns true if the user granted permission, false otherwise.
  Future<bool> requestPermission() async {
    return await _api.requestPermission();
  }

  /// Writes mindful minutes to the system.
  /// [startTime] and [endTime] are the start and end times of
  /// mindful minutes exercised.
  Future<void> writeMindfulMinutes(DateTime startTime, DateTime endTime) async {
    // Communication between platforms is done in seconds.
    await _api.writeMindfulMinutes(
      (startTime.millisecondsSinceEpoch / 1000).toInt(),
      (endTime.millisecondsSinceEpoch / 1000).toInt(),
    );
  }

}
